<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S9324RI" failures="0" tests="7" name="testNG_Package.Randomtime" time="0.188" errors="1" timestamp="06 Oct 2018 02:46:09 GMT" skipped="0">
  <testcase classname="testNG_Package.Randomtime" name="Remaining_Minutes" time="0.000"/>
  <testcase classname="testNG_Package.Randomtime" name="Elapsed_minutes" time="0.016"/>
  <testcase classname="testNG_Package.Randomtime" name="Random_Time_After_Added" time="0.015"/>
  <testcase classname="testNG_Package.Randomtime" name="RandomTime_into_LocalTime" time="0.016"/>
  <testcase classname="testNG_Package.Randomtime" name="Cron_Tab" time="0.047">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testNG_Package.Randomtime.Cron_Tab(Randomtime.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Cron_Tab -->
  <testcase classname="testNG_Package.Randomtime" name="Random_Minutes" time="0.000"/>
  <testcase classname="testNG_Package.Randomtime" name="Current_local_Time" time="0.094"/>
</testsuite> <!-- testNG_Package.Randomtime -->
